name: "\U0001F41B Bug Report"
description: "There is something that is not working as expected."
title: "Bug Report: "
labels: ["triage", "bug"]
body:

  - type: markdown
    attributes:
      value: |
        ### :warning: Please, make sure you're creating an issue for the right repository!

        ---

  - type: checkboxes
    attributes:
      label: "Is there an existing issue for this?"
      description: "Please search [here](../issues?q=is%3Aissue) to see if an issue already exists for the bug you encountered"
      options:
      - label: "I have searched the existing issues"
        required: true

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Current behavior"
      description: "What is going on?"

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Steps to reproduce"
      description: |
        How does the problem manifest itself? What did you do for this?
      placeholder: |
        1. `npm ci`
        2. `npm start:dev`
        3. See error...

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happened (or code)."

  - type: input
    validations:
      required: true
    attributes:
      label: "Package version"
      description: |
        Which version of the package (service, app, tool) are you using?

        :warning: **Make sure you are using an unmodified package that matches the version!**
      placeholder: "1.2.3"

  - type: input
    attributes:
      label: "Node.js version"
      description: "Which version of Node.js are you using?"
      placeholder: "14.17.6"

  - type: checkboxes
    validations:
      required: true
    attributes:
      label: "In which operating systems have you tested?"
      options:
        - label: macOS
        - label: Windows
        - label: Linux

  - type: textarea
    attributes:
      label: "Suggested fix"
      description: "Can you suggest how to solve this issue?"

  - type: textarea
    attributes:
      label: "Other"
      description: |
        Anything else relevant? eg: Logs, IDE, package manager, etc.
